//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JcoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement
    {
        public Announcement()
        {
            this.AssignAnnouncements = new HashSet<AssignAnnouncement>();
        }
    
        public long AnnouncementId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public System.DateTime PublishDate { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public long CreatedBy { get; set; }
    
        public virtual TblUser TblUser { get; set; }
        public virtual ICollection<AssignAnnouncement> AssignAnnouncements { get; set; }
    }
}
