//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JcoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignAnnouncement
    {
        public long AssignAnnouncementId { get; set; }
        public long AnnouncementId { get; set; }
        public long UserId { get; set; }
    
        public virtual Announcement Announcement { get; set; }
        public virtual TblUser TblUser { get; set; }
    }
}
