//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JcoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignDuty
    {
        public AssignDuty()
        {
            this.RequestTrades = new HashSet<RequestTrade>();
        }
    
        public long AssignDutyId { get; set; }
        public long DutyId { get; set; }
        public long AgentId { get; set; }
        public string RTS { get; set; }
        public Nullable<bool> UserAvailable { get; set; }
        public string trade_message { get; set; }
    
        public virtual TblUser TblUser { get; set; }
        public virtual Duty Duty { get; set; }
        public virtual ICollection<RequestTrade> RequestTrades { get; set; }
    }
}
