//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JcoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyProfile
    {
        public long ProfileId { get; set; }
        public string Logo { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}
