//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JcoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duty
    {
        public Duty()
        {
            this.AssignDuties = new HashSet<AssignDuty>();
        }
    
        public long DutyId { get; set; }
        public string Location { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public string RoadshowCode { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual ICollection<AssignDuty> AssignDuties { get; set; }
    }
}
