//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JcoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.AgentEventParticipates = new HashSet<AgentEventParticipate>();
            this.Guests = new HashSet<Guest>();
        }
    
        public long EventId { get; set; }
        public string EventName { get; set; }
        public string Description { get; set; }
        public System.DateTime EventDate { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public int AgentSeat { get; set; }
        public bool IsGuestRegistration { get; set; }
        public int GuestSeat { get; set; }
        public System.DateTime RSVP_By { get; set; }
        public string RSVP_Time { get; set; }
        public long CreatedBy { get; set; }
    
        public virtual ICollection<AgentEventParticipate> AgentEventParticipates { get; set; }
        public virtual TblUser TblUser { get; set; }
        public virtual ICollection<Guest> Guests { get; set; }
    }
}
