//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JcoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public long GuestId { get; set; }
        public long EventId { get; set; }
        public long AgentId { get; set; }
        public string GuestName { get; set; }
        public string NRIC_OR_ID { get; set; }
        public string Age { get; set; }
        public string GuestEmail { get; set; }
        public string Mobile { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual TblUser TblUser { get; set; }
    }
}
