//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JcoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inception
    {
        public long InceptionId { get; set; }
        public long MonthFrom { get; set; }
        public long YearFrom { get; set; }
        public long AgentId { get; set; }
        public decimal MTD_WAPI { get; set; }
        public decimal YTD_WAPI { get; set; }
    
        public virtual TblUser TblUser { get; set; }
    }
}
