//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JcoDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JCOEntities : DbContext
    {
        public JCOEntities()
            : base("name=JCOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AgentEventParticipate> AgentEventParticipates { get; set; }
        public DbSet<Announcement> Announcements { get; set; }
        public DbSet<Award> Awards { get; set; }
        public DbSet<CompanyProfile> CompanyProfiles { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<Guest> Guests { get; set; }
        public DbSet<ManagerdistributeAmount> ManagerdistributeAmounts { get; set; }
        public DbSet<Poll> Polls { get; set; }
        public DbSet<PollOption> PollOptions { get; set; }
        public DbSet<PollResult> PollResults { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<RoleAssignment> RoleAssignments { get; set; }
        public DbSet<Subject> Subjects { get; set; }
        public DbSet<TblUser> TblUsers { get; set; }
        public DbSet<Duty> Duties { get; set; }
        public DbSet<Inception> Inceptions { get; set; }
        public DbSet<UserDocument> UserDocuments { get; set; }
        public DbSet<AssignAnnouncement> AssignAnnouncements { get; set; }
        public DbSet<AssignPollingAgent> AssignPollingAgents { get; set; }
        public DbSet<AssignDuty> AssignDuties { get; set; }
        public DbSet<RequestTrade> RequestTrades { get; set; }
    }
}
