//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JcoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PollOption
    {
        public PollOption()
        {
            this.PollResults = new HashSet<PollResult>();
        }
    
        public long PollOptionId { get; set; }
        public string Options { get; set; }
        public bool IsTrue { get; set; }
        public long PollId { get; set; }
    
        public virtual Poll Poll { get; set; }
        public virtual ICollection<PollResult> PollResults { get; set; }
    }
}
