//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JcoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestTrade
    {
        public long RequestTradeId { get; set; }
        public long RequestAgentId { get; set; }
        public string Message { get; set; }
        public long AssignDutyId { get; set; }
        public bool Accept { get; set; }
    
        public virtual AssignDuty AssignDuty { get; set; }
        public virtual TblUser TblUser { get; set; }
    }
}
