//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JcoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUser
    {
        public TblUser()
        {
            this.AgentEventParticipates = new HashSet<AgentEventParticipate>();
            this.Announcements = new HashSet<Announcement>();
            this.Awards = new HashSet<Award>();
            this.Events = new HashSet<Event>();
            this.Guests = new HashSet<Guest>();
            this.ManagerdistributeAmounts = new HashSet<ManagerdistributeAmount>();
            this.ManagerdistributeAmounts1 = new HashSet<ManagerdistributeAmount>();
            this.Polls = new HashSet<Poll>();
            this.PollResults = new HashSet<PollResult>();
            this.Roles = new HashSet<Role>();
            this.Roles1 = new HashSet<Role>();
            this.RoleAssignments = new HashSet<RoleAssignment>();
            this.Subjects = new HashSet<Subject>();
            this.Inceptions = new HashSet<Inception>();
            this.UserDocuments = new HashSet<UserDocument>();
            this.AssignAnnouncements = new HashSet<AssignAnnouncement>();
            this.AssignPollingAgents = new HashSet<AssignPollingAgent>();
            this.AssignDuties = new HashSet<AssignDuty>();
            this.RequestTrades = new HashSet<RequestTrade>();
        }
    
        public long UserId { get; set; }
        public long RoleId { get; set; }
        public string Name { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public string Mobile { get; set; }
        public string Photo { get; set; }
        public string AgentCode { get; set; }
        public string JoinDate { get; set; }
        public string Designation { get; set; }
        public string Gender { get; set; }
        public string DOB { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<long> ManagerID { get; set; }
        public Nullable<decimal> AgentTarget { get; set; }
        public string DeviceId { get; set; }
    
        public virtual ICollection<AgentEventParticipate> AgentEventParticipates { get; set; }
        public virtual ICollection<Announcement> Announcements { get; set; }
        public virtual ICollection<Award> Awards { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Guest> Guests { get; set; }
        public virtual ICollection<ManagerdistributeAmount> ManagerdistributeAmounts { get; set; }
        public virtual ICollection<ManagerdistributeAmount> ManagerdistributeAmounts1 { get; set; }
        public virtual ICollection<Poll> Polls { get; set; }
        public virtual ICollection<PollResult> PollResults { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<Role> Roles1 { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<RoleAssignment> RoleAssignments { get; set; }
        public virtual ICollection<Subject> Subjects { get; set; }
        public virtual ICollection<Inception> Inceptions { get; set; }
        public virtual ICollection<UserDocument> UserDocuments { get; set; }
        public virtual ICollection<AssignAnnouncement> AssignAnnouncements { get; set; }
        public virtual ICollection<AssignPollingAgent> AssignPollingAgents { get; set; }
        public virtual ICollection<AssignDuty> AssignDuties { get; set; }
        public virtual ICollection<RequestTrade> RequestTrades { get; set; }
    }
}
